FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "target/web-scraping-ta-0.0.1-SNAPSHOT.jar"]
#
# # 1. Gunakan image dasar Java 17
# FROM openjdk:17-jdk-slim
#
# # 2. Tentukan direktori kerja di dalam container
# WORKDIR /app
#
# # 3. Copy semua file dari direktori lokal ke direktori kerja container
# COPY . .
#
# # 4. Jalankan perintah build dengan Maven wrapper
# RUN ./mvnw clean package -DskipTests
#
# # 5. Jalankan aplikasi Spring Boot
# CMD ["java", "-jar", "target/WebScrapingTaApplication.jar"]
